apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: secrets-watch-demo
type: Opaque
stringData:
  username: "initial-user"
  password: "initial-password"
  api-key: "initial-api-key-12345"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: secrets-watch-demo
type: Opaque
stringData:
  db-user: "db-user-initial"
  db-password: "db-pass-initial"
  connection-string: "mysql://db-user-initial:db-pass-initial@mysql:3306/testdb"