apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: secrets-watch-demo
type: Opaque
stringData:
  username: "updated-user"
  password: "updated-password"
  api-key: "updated-api-key-67890"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: secrets-watch-demo
type: Opaque
stringData:
  db-user: "db-user-updated"
  db-password: "db-pass-updated"
  connection-string: "mysql://db-user-updated:db-pass-updated@mysql:3306/testdb"